###########
# site.title

title:    'Greedy-Panicky--Grab-Those-Patty'
subtitle: 'CS 175: Minecraft AI based on A-star policy'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
