###########
# site.title

title:    'Greedy-Panicky--Grab-Those-Patty'
subtitle: 'CS 175: Project in AI (in Minecraft)'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
